### ISSUE TITLE
Tweak the result's display as per attached image

### ISSUE THREAD

**Issue by st3v3nhunt** [nhsalpha/connecting-to-services-hack-day#58]
![pasted image at 2016_07_28 04_37 pm](https://cloud.githubusercontent.com/assets/639706/17219525/9807e87a-54e3-11e6-8356-c9b6a7195acc.png)

**Comment by ermlikeyeah** [comment]
For reference there is a page here:
http://connecting-to-services-design.herokuapp.com/sprint-39/research/stomach-ache-services

**Comment by ermlikeyeah** [comment]
"Is it open?"

If it is open: `Currently open until {closing time}.`

It is closed today/for the rest of today: `Closed. Opens next tomorrow at {tomorrow opening time} to {tomorrow closing time}.`

If it is closed but opens later today: `Closed. Opens today at {opening time} until {today closing time}.`

If it is closed but opens in the next 90 minutes: `Closed. Opens soon at {today opening time} until {today closing time}.`

**Comment by ermlikeyeah** [comment]
All times in AM/PM format rather than 24hr format,
